version: "2.1"
orbs:
  node: circleci/node@4.3.0

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 16.3.0
          run-command: "test"
      - node/test:
          version: 14.17.1
          run-command: "test"
      - node/test:
          version: 12.22.1
          run-command: "test"
      - node/test:
          version: 10.24.1
          run-command: "test"

  test-with-coverage:
    jobs:
      - node/test:
          run-command: "test:ci-coverage"

  build-test:
    jobs:
      - node/test:
          run-command: "build"
